'''
  You are given two strings s and t.
  String t is generated by random shuffling string s and then add one more letter at a random position.
  Return the letter that was added to t. 

  Input: s = "abcd", t = "abcde"
  Output: "e"
  Explanation: 'e' is the letter that was added.

  Input: s = "a", t = "aa"
  Output: "a"
'''

class Solution:
  def findTheDifference(self, s: str, t: str) -> str:
    for i in t:
      if s.count(i) != t.count(i): return i

class Solution:
  def findTheDifference(self, s: str, t: str) -> str:
      return list(Counter(t) - Counter(s))[0]